version: '3.6'
services:
  fuseki:
    image: local-dev/rp-ucd-harvest-person:main
    ports:
      - "3030:3030"
    environment:
      - CDL_AUTH=ucd:4eKuwAhZLG
      - UCDID_AUTH=ucd:75b4442-c7e1a-3f77e05-3662178800710

    tmpfs:
      - /var/lib/fuseki/databases/harvest
      - /home/ucd.process/cdl
    command: tail -f /dev/null
#    volumes:
#      - type: tmpfs
#        target: /var/lib/fuseki/databases/harvest
#        tmpfs:
#          size: 1000000000
#      - ./iam.hdt:/var/lib/fuseki/hdt/iam.hdt

#volumes:
#  ae-grants:
#    external:true
#  ae-iam:
#    external:true

#network:
#  default:
#    name:ae-harvest
