* Jena Fuseki HDT

 The idea here is create a more agile fuseki/jena system that can be used to
 create the file based inputs for our cloud computing environment.  So multiple
 versions can be started up at any given time, and used to poppulate the cloud
 based services.

 In addition, we hope this can be added to Apache Workflow in order to better
 manage the task of incrementally adding up the users

 We are trying to use the standard [[https://jena.apache.org/documentation/fuseki2/fuseki-layout.html][fuseki layout]], FUSEKI_HOME and FUSEKI_BASE.
 This allows us to have the configuration files in the image.  The databases are
 not in their default location, but are instead at: /var/lib/fuseki/databases.
 The fuseki layout file identifies that we need remove the ${FUSEKI_BASE}/system
 and ${FUSEKI_BASE}/system_files to reset the server.

 Some good review of all of Jena's tools are found in this [[https://www.bobdc.com/blog/jenagems/][blog post]].


** Docker instance

   The Dockerfile is a combination of the hdt-java project, and the Apache Jena
   project.  These are controlled at build time with the HDT_VERSION, and
   JENA_VERSION parameters.  The hdt is an intermediate build using maven, which
   then copies some jars into the fuseki extras directory.

   The fuseki instance actually copies existing jars from the apache jena repo,
   and adds them to the image.

** Running the image

   The docker image entrypoint ends by starting the FUSEKI endpoint. This means
   that to properly configure this, you need to setup files in the
   /etc/fuseki/configuation location.

   See the [[file:hdt-example][hdt-example]] directory for an example configuration
